[package]
name = "mobius"
version = "0.1.0"
edition = "2024"

[dependencies]
# The standard asynchronous runtime for Rust
tokio = { version = "1.37", features = ["full"] }
# The HTTP client, with the "json" feature enabled
reqwest = { version = "0.12", features = ["json"] }
# For easily creating and parsing JSON objects
serde_json = "1.0"
reedline = "0.38"
